vim.keymap.set('n', '<leader>gd', '<cmd>DiffviewOpen<cr>', { desc = '[G]it [d]iff (index)' })
vim.keymap.set('n', '<leader>gD', '<cmd>DiffviewOpen HEAD~1<cr>', { desc = '[G]it [D]iff last commit' })
vim.keymap.set('n', '<leader>go', '<cmd>DiffviewOpen origin/HEAD..HEAD<cr>', { desc = '[G]it diff [o]rigin' })
vim.keymap.set('n', '<leader>gh', '<cmd>DiffviewFileHistory<cr>', { desc = '[G]it [h]istory (repo)' })
vim.keymap.set('n', '<leader>gH', '<cmd>DiffviewFileHistory %<cr>', { desc = '[G]it [H]istory (file)' })
vim.keymap.set('n', '<leader>gc', '<cmd>DiffviewClose<cr>', { desc = '[G]it [c]lose diffview' })
